### ISSUE TITLE
Bug download error 

### ISSUE THREAD

**Issue by bianvigano** [Zeptosec/Streamer#1]
error thermastore.netlify.app
![Screenshot from 2023-12-07 18-06-33](https://github.com/Zeptosec/Streamer/assets/12135917/8298376f-bba2-45bf-94cd-e26a67458975)

and 

I have updated this and made some modifications.
![Screenshot from 2023-12-07 18-08-08](https://github.com/Zeptosec/Streamer/assets/12135917/cb469945-afd9-45c9-9056-9274f92b4cc7)
![Screenshot from 2023-12-07 18-08-19](https://github.com/Zeptosec/Streamer/assets/12135917/9512ec66-0515-4c4f-bcb2-e211cece6e8b)

**Comment by Zeptosec** [comment]
Possible problems:
- Cors misconfiguration issue.
- Chrome plugins blocking requests (ad blockers, other protection plugins)

https://github.com/axios/axios/issues/5644#issuecomment-1761974993
